-- AlterEnum: Add new values to TrialPhase enum
ALTER TYPE "TrialPhase" ADD VALUE IF NOT EXISTS 'EARLY_PHASE_1';
ALTER TYPE "TrialPhase" ADD VALUE IF NOT EXISTS 'NOT_APPLICABLE';

-- AlterEnum: Add new values to TrialStatus enum
ALTER TYPE "TrialStatus" ADD VALUE IF NOT EXISTS 'NOT_YET_RECRUITING';
ALTER TYPE "TrialStatus" ADD VALUE IF NOT EXISTS 'ACTIVE_NOT_RECRUITING';
ALTER TYPE "TrialStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN';
ALTER TYPE "TrialStatus" ADD VALUE IF NOT EXISTS 'ENROLLING_BY_INVITATION';
ALTER TYPE "TrialStatus" ADD VALUE IF NOT EXISTS 'UNKNOWN';
